#!/bin/sh
########################################################################
# Begin nova
#
# Description : OpenStack Nova Compute Service
#
###
### Generated by Grok 3
###     1. Previously uploaded /lib/lsb/init-functions
###     2. from init.d, upload sysklogd, network, ntpd, sshd, httpd, mysql, gpm
###
### using the phrase:
###     OpenStack: using LfS 12.2 sysvinit,
###     already installed MariaDB, Apache, RabbitMQ, MemCacheD, etcd,
###     KeyStone, Glance, Placement.
###     how to install Nova-30.0.0 from source?
###  then added
###     noVNC app
###
# Author      : Grok 3
# Version     : Nova 30.0.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            nova
# Required-Start:      $network mariadb rabbitmq-server memcached keystone
# Should-Start:        glance placement
# Required-Stop:       $network
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts OpenStack Nova services.
# Description:         Controls OpenStack Nova compute services.
# X-LFS-Provided-By:   Custom
### END INIT INFO

. /lib/lsb/init-functions

#NOVA_HOME=/usr/local
NOVA_HOME=/usr/
NOVA_BIN=$NOVA_HOME/bin
NOVA_CONFIG=/etc/nova/nova.conf
NOVA_LOGDIR=/var/log/nova
PID_DIR=/var/run/nova
mkdir -p $PID_DIR
chown nova:nova $PID_DIR

case "$1" in
   start)
      log_info_msg "Starting Nova API..."
#      start_daemon -u nova $NOVA_BIN/nova-api --config-file=/etc/nova/nova.conf
#      su - nova -c "$NOVA_BIN/nova-api --config-file=$NOVA_CONFIG --log-dir=$NOVA_LOGDIR &""
      $NOVA_BIN/nova-api --config-file=$NOVA_CONFIG --log-dir=$NOVA_LOGDIR &
      evaluate_retval

      log_info_msg "Starting Nova Scheduler..."
#      start_daemon -u nova $NOVA_BIN/nova-scheduler --config-file=/etc/nova/nova.conf
      $NOVA_BIN/nova-scheduler --config-file=$NOVA_CONFIG --log-dir=$NOVA_LOGDIR &
      evaluate_retval

      log_info_msg "Starting Nova Conductor..."
#      start_daemon -u nova $NOVA_BIN/nova-conductor --config-file=/etc/nova/nova.conf
      $NOVA_BIN/nova-conductor --config-file=$NOVA_CONFIG --log-dir=$NOVA_LOGDIR &
      evaluate_retval

      log_info_msg "Starting Nova NoVNC Proxy..."
      $NOVA_BIN/nova-novncproxy --config-file=$NOVA_CONFIG --log-dir=$NOVA_LOGDIR &
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping Nova NoVncProxy..."
      killproc $NOVA_BIN/nova-novncproxy
      evaluate_retval

      log_info_msg "Stopping Nova Conductor..."
      killproc $NOVA_BIN/nova-conductor
      evaluate_retval

      log_info_msg "Stopping Nova Scheduler..."
      killproc $NOVA_BIN/nova-scheduler
      evaluate_retval

      log_info_msg "Stopping Nova API..."
      killproc $NOVA_BIN/nova-api
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      statusproc $NOVA_BIN/nova-api
      statusproc $NOVA_BIN/nova-scheduler
      statusproc $NOVA_BIN/nova-conductor
      statusproc $NOVA_BIN/nova-novncproxy
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

exit 0

# End nova