#!/bin/sh
# /etc/rc.d/init.d/rabbitmq
# Startup script for RabbitMQ Server under SysV init

###
### Generated by Grok 3 using the phrase:
###   linux from scratch 12.2 sysv init
###   how to startup rabbitmq-server during boot time?
###

# Source function library (if available, optional in LFS)
#. /etc/rc.d/init.d/functions

# RabbitMQ settings
RABBITMQ_SERVER=/usr/local/sbin/rabbitmq-server
RABBITMQ_CTL=/usr/local/sbin/rabbitmqctl
RABBITMQ_PID_FILE=/var/run/rabbitmq.pid
RABBITMQ_USER=rabbitmq  # User to run RabbitMQ (create this user if needed)

start() {
    echo -n "Starting RabbitMQ Server: "
    if [ -f "$RABBITMQ_PID_FILE" ]; then
        echo "RabbitMQ is already running."
        return 1
    fi
    # FAILED
    # su - $RABBITMQ_USER -c "$RABBITMQ_SERVER -detached"
    $RABBITMQ_SERVER -detached
    sleep 5
    $RABBITMQ_CTL start_app
    sleep 5  # Give it time to start
    if $RABBITMQ_CTL status > /dev/null 2>&1; then
        echo "OK"
        return 0
    else
        echo "FAILED"
        return 1
    fi
}

stop() {
    echo -n "Stopping RabbitMQ Server: "
    $RABBITMQ_CTL stop
    sleep 2  # Wait for shutdown
    if [ ! -f "$RABBITMQ_PID_FILE" ]; then
        echo "OK"
        return 0
    else
        echo "FAILED"
        return 1
    fi
}

status() {
    $RABBITMQ_CTL status
    if [ $? -eq 0 ]; then
        echo "RabbitMQ is running."
        return 0
    else
        echo "RabbitMQ is stopped."
        return 3
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 2
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit $?
