#!/bin/sh

### Generated by Grok 2025/Oct/23

#!/bin/sh
. /lib/lsb/init-functions

name="etcd"
program="/usr/local/bin/etcd"
pidfile="/run/etcd/etcd.pid"
logfile="/var/log/etcd/etcd.log"
args="--config-file /etc/etcd.conf.yml"

start() {
    log_info_msg "Starting $name..."
    
    # Check if already running
    pidofproc -p "$pidfile" "$program" >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        log_success_msg2
        return 0
    fi
    
    # Create pid directory if it doesn't exist
    install -d -m 755 -o etcd -g etcd /run/etcd
    
    # Start as etcd user and capture PID
    su -s /bin/sh etcd -c "cd /var/lib/etcd && $program $args >> $logfile 2>&1 & echo \$! > $pidfile"
    
    # Wait a moment for process to start
    sleep 1
    
    # Verify it's running
    if pidofproc -p "$pidfile" "$program" >/dev/null 2>&1; then
        log_success_msg2
    else
        log_failure_msg2
        rm -f "$pidfile"
    fi
}

stop() {
    log_info_msg "Stopping $name..."
    killproc -p "$pidfile" "$program"
    rm -f "$pidfile"
    evaluate_retval
}

case "$1" in
    start) start ;;
    stop)  stop  ;;
    restart) stop; sleep 1; start ;;
    status) statusproc -p "$pidfile" "$program" ;;
    *) echo "Usage: $0 {start|stop|restart|status}"; exit 1 ;;
esac
