#!/bin/sh
########################################################################
# Begin rabbitmq
#
# Description : RabbitMQ Server Control Script
#
###
### Generated by Grok 3
###     1. Upload first /lib/lsb/init-functions
###     2. from init.d, upload sysklogd, network, ntpd, sshd, httpd, mysql, gpm
###
### using the phrase:
###     https://github.com/rabbitmq/rabbitmq-server/releases/download/v4.1.4/rabbitmq-server-generic-unix-4.1.4.tar.xz
###     How can I install RabbitMQ (based on link)? include init scripts
###
#
# Author      : Grok 3
# Version     : RabbitMQ 4.1.4 (was based on RabbitMQ 4.0.3)
#
########################################################################

### BEGIN INIT INFO
# Provides:            rabbitmq
# Required-Start:      $network
# Should-Start:        $syslog
# Required-Stop:       $network
# Should-Stop:         $syslog
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts RabbitMQ server.
# Description:         Controls the RabbitMQ messaging server.
# X-LFS-Provided-By:   Custom
### END INIT INFO

. /lib/lsb/init-functions

# RABBITMQ_HOME=/usr/local/rabbitmq_server-4.0.3
# RABBITMQ_SBIN=$RABBITMQ_HOME/sbin

# Set PATH to include /usr/local/bin where erl and escript are located
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH

# Set UTF-8 locale to avoid Elixir encoding warning
export LANG=C.UTF-8

RABBITMQ_SBIN=/usr/local/sbin
PIDFILE=/var/run/rabbitmq.pid
export HOME=/var/lib/rabbitmq  # Enforce cookie location
export RABBITMQ_ERLANG_COOKIE="OPENSTACK"  # Optional: enforce specific cookie

case "$1" in
   start)
      log_info_msg "Starting RabbitMQ server..."
      start_daemon $RABBITMQ_SBIN/rabbitmq-server -detached
      sleep 5
      $RABBITMQ_SBIN/rabbitmqctl start_app
      sleep 5
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping RabbitMQ server..."
      $RABBITMQ_SBIN/rabbitmqctl shutdown
      evaluate_retval
      [ -f "$PIDFILE" ] && rm -f "$PIDFILE"
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      statusproc $RABBITMQ_SBIN/rabbitmq-server
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

exit 0

# End rabbitmq
