#!/bin/sh

###
### Generated by Grok 2025/Oct/23
###
###     1. Upload first /lib/lsb/init-functions
###
### using the phrase:
###     attached file is /lib/lsb/init-functions,
###     lfs 12.4, sysvinit
###     memcached, build from source
###     http://www.memcached.org/files/memcached-1.6.39.tar.gz
###     groupadd -g 441 memcached &&
###     useradd -c "MemCacheD" -g memcached -d /var/lib/memcached \
###         -s /bin/false -u 441 memcached &&
###     ./configure --prefix=/usr/local/ --with-libevent=/usr \
###         --sysconfdir=/etc &&
###     make &&
###     make install
###     /etc/memcached/conf contains -l 10.0.0.11
###     mkdir -pv /var/{lib,run,log}/memcached &&
###     chown -vR memcached:memcached /var/{lib,run,log}/memcached
###     create init scripts

### BEGIN INIT INFO
# Provides:          memcached
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: memcached daemon
# Description:       memcached is a high-performance, distributed memory
#                    object caching system
### END INIT INFO

# Source LSB init functions
. /lib/lsb/init-functions

# Pull in sysconfig settings if available, otherwise set defaults
[ -f /etc/sysconfig/memcached ] && . /etc/sysconfig/memcached

MEMCACHED_BIN="${MEMCACHED_BIN:-/usr/local/bin/memcached}"
PIDFILE="${PIDFILE:-/var/run/memcached/memcached.pid}"
USER="${USER:-memcached}"
PORT="${PORT:-11211}"
MAXCONN="${MAXCONN:-1024}"
CACHESIZE="${CACHESIZE:-64}"
OPTIONS="${OPTIONS:--l 10.0.0.11}"  # Default to the provided listen address; override with sysconfig if needed

# If /etc/memcached/conf exists, use it for additional options
if [ -f /etc/memcached/conf ]; then
    OPTIONS="$(cat /etc/memcached/conf)"
fi

# Full start options, including daemonize, pidfile, user, etc.
START_OPTS="-d -p ${PORT} -u ${USER} -m ${CACHESIZE} -c ${MAXCONN} -P ${PIDFILE} ${OPTIONS}"

start() {
    log_info_msg "Starting memcached..."
    # Ensure run directory exists
    mkdir -p /var/run/memcached
    chown ${USER}:${USER} /var/run/memcached
    start_daemon ${MEMCACHED_BIN} ${START_OPTS}
    evaluate_retval
}

stop() {
    log_info_msg "Stopping memcached..."
    killproc -p ${PIDFILE} ${MEMCACHED_BIN} -TERM
    evaluate_retval
}

case "${1}" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        ${0} stop
        sleep 1
        ${0} start
        ;;
    status)
        statusproc -p ${PIDFILE} ${MEMCACHED_BIN}
        ;;
    *)
        echo "Usage: ${0} {start|stop|restart|force-reload|status}"
        exit 1
        ;;
esac

exit 0
