#!/bin/sh

###
### Generated by Grok 2025/Oct/18
###
###     1. Upload first /lib/lsb/init-functions
###     2. from init.d
###
### using the phrase:
###     how to install Open vSwitch on Controller node?
###

### BEGIN INIT INFO
# Provides:          openvswitch-switch
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Open vSwitch
# Description:       Manages Open vSwitch daemons
### END INIT INFO

. /lib/lsb/init-functions

PROGRAM="ovs-vswitchd"
BINARY="/usr/sbin/${PROGRAM}"
PIDFILE="/var/run/openvswitch/${PROGRAM}.pid"
LOGFILE="/var/log/openvswitch/${PROGRAM}.log"
OVS_CTL="/usr/share/openvswitch/scripts/ovs-ctl"

case "$1" in
  start)
    log_info_msg "Starting ${PROGRAM}..."
    ${OVS_CTL} start --system-id=random
    evaluate_retval
    ;;
  stop)
    log_info_msg "Stopping ${PROGRAM}..."
    ${OVS_CTL} stop
    evaluate_retval
    ;;
  restart|force-reload)
    $0 stop
    $0 start
    ;;
  status)
    statusproc -p "${PIDFILE}" "${BINARY}"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
