#!/bin/sh

# Generated by Grok 2025/Nov/03

### BEGIN INIT INFO
# Provides:          ovn-dbs
# Required-Start:    $local_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OVN Northbound and Southbound Databases
### END INIT INFO

# --- Load LSB functions ---
. /lib/lsb/init-functions

# --- Configuration ---
DB_DIR=/var/lib/ovn
RUN_DIR=/var/run/ovn
LOG_DIR=/var/log/ovn

NB_DB="$DB_DIR/ovnnb_db.db"
SB_DB="$DB_DIR/ovnsb_db.db"
NB_SOCK="$RUN_DIR/ovnnb_db.sock"
SB_SOCK="$RUN_DIR/ovnsb_db.sock"
NB_PID="$RUN_DIR/ovnnb_db.pid"
SB_PID="$RUN_DIR/ovnsb_db.pid"
NB_LOG="$LOG_DIR/ovnnb_db.log"
SB_LOG="$LOG_DIR/ovnsb_db.log"

# --- Ensure directories ---
prepare_logs() {
    install -v -d -m 2755 "$RUN_DIR"
#    install -v -d -m 2755 "$LOG_DIR"
#    install -v -d -m 0755 "$DB_DIR"
    touch "$NB_LOG" "$SB_LOG"
    chmod 644 "$NB_LOG" "$SB_LOG"
}

# --- Start OVN Databases ---
start_ovn_dbs() {
    log_info_msg "Starting OVN databases..."
    prepare_logs

    # Start Northbound DB
    if [ -f "$NB_PID" ] && kill -0 $(cat "$NB_PID") 2>/dev/null; then
        log_success_msg "OVN Northbound DB already running"
    else
        log_info_msg "Starting OVN Northbound DB..."
        ovsdb-server \
            --remote=punix:"$NB_SOCK" \
            --remote=ptcp:6641:127.0.0.1 \
            --pidfile="$NB_PID" \
            --detach \
            --log-file="$NB_LOG" \
            --verbose \
            "$NB_DB" > /dev/null 2>&1

        if [ -f "$NB_PID" ] && kill -0 $(cat "$NB_PID") 2>/dev/null; then
            log_success_msg "OVN Northbound DB started"
        else
            log_failure_msg "Failed to start OVN Northbound DB"
            return 1
        fi
    fi

    # Start Southbound DB
    if [ -f "$SB_PID" ] && kill -0 $(cat "$SB_PID") 2>/dev/null; then
        log_success_msg "OVN Southbound DB already running"
    else
        log_info_msg "Starting OVN Southbound DB..."
        ovsdb-server \
            --remote=punix:"$SB_SOCK" \
            --remote=ptcp:6642:127.0.0.1 \
            --pidfile="$SB_PID" \
            --detach \
            --log-file="$SB_LOG" \
            --verbose \
            "$SB_DB" > /dev/null 2>&1

        if [ -f "$SB_PID" ] && kill -0 $(cat "$SB_PID") 2>/dev/null; then
            log_success_msg "OVN Southbound DB started"
        else
            log_failure_msg "Failed to start OVN Southbound DB"
            return 1
        fi
    fi
}

# --- Stop OVN Databases ---
stop_ovn_dbs() {
    log_info_msg "Stopping OVN databases..."

    # Stop Northbound
    if [ -f "$NB_PID" ] && kill -0 $(cat "$NB_PID") 2>/dev/null; then
        log_info_msg "Stopping OVN Northbound DB..."
        kill $(cat "$NB_PID")
        rm -f "$NB_PID"
        log_success_msg "OVN Northbound DB stopped"
    else
        log_success_msg "OVN Northbound DB not running"
    fi

    # Stop Southbound
    if [ -f "$SB_PID" ] && kill -0 $(cat "$SB_PID") 2>/dev/null; then
        log_info_msg "Stopping OVN Southbound DB..."
        kill $(cat "$SB_PID")
        rm -f "$SB_PID"
        log_success_msg "OVN Southbound DB stopped"
    else
        log_success_msg "OVN Southbound DB not running"
    fi
}

# --- Status ---
status_ovn_dbs() {
    echo "=== OVN Database Status ==="

    if [ -f "$NB_PID" ] && kill -0 $(cat "$NB_PID") 2>/dev/null; then
        echo "OVN Northbound DB: RUNNING (PID $(cat $NB_PID))"
    else
        echo "OVN Northbound DB: STOPPED"
    fi

    if [ -f "$SB_PID" ] && kill -0 $(cat "$SB_PID") 2>/dev/null; then
        echo "OVN Southbound DB: RUNNING (PID $(cat $SB_PID))"
    else
        echo "OVN Southbound DB: STOPPED"
    fi
}

# --- Main ---
case "$1" in
    start)
        start_ovn_dbs
        ;;
    stop)
        stop_ovn_dbs
        ;;
    restart)
        stop_ovn_dbs
        sleep 1
        start_ovn_dbs
        ;;
    status)
        status_ovn_dbs
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
