#!/bin/sh

###
### Generated by Grok 2025/Oct/18
###
###     1. Upload first /lib/lsb/init-functions
###     2. from init.d
###
### using the phrase:
###     attached file is at /lib/lsb/init-functions
###     openstack
###     https://www.openvswitch.org/releases/openvswitch-3.3.6.tar.gz
###     https://www.openvswitch.org/
###     https://docs.openvswitch.org/en/latest/
###     https://docs.openvswitch.org/en/latest/intro/install/general/
###     how to install openvswitch
###     on lfs 12.4 sysvinit?
###

########################################################################
# Begin openvswitch
#
# Description : Open vSwitch Init Script
#
# Authors     : Adapted from OVS Debian/RHEL scripts for LFS
#
# Version     : LFS 12.4
#
########################################################################

. /lib/lsb/init-functions

PATH=$PATH:/usr/share/openvswitch/scripts

case "$1" in
   start)
      log_info_msg "Starting Open vSwitch..."
      ovs-ctl start --system-id=random --system-version="12.4" --system-type="linux"
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping Open vSwitch..."
      ovs-ctl stop
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      statusproc /usr/local/bin/ovs-vswitchd
      statusproc /usr/local/bin/ovsdb-server
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

# End openvswitch
