#!/bin/sh

# Generated by Grok 2025/Nov/02

### BEGIN INIT INFO
# Provides:          ovn-dbs
# Required-Start:    $local_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OVN Databases
### END INIT INFO

case "$1" in
  start)
    echo "Starting OVN DBs..."
    ovsdb-server --pidfile=/var/run/ovn/ovnnb_db.pid \
        --remote=punix:/var/run/ovn/ovnnb_db.sock \
        --remote=ptcp:6641:127.0.0.1 \
        /var/lib/ovn/ovnnb_db.db &

    ovsdb-server --pidfile=/var/run/ovn/ovnsb_db.pid \
        --remote=punix:/var/run/ovn/ovnsb_db.sock \
        --remote=ptcp:6642:127.0.0.1 \
        /var/lib/ovn/ovnsb_db.db &
    ;;

  stop)
    kill $(cat /var/run/ovn/ovnnb_db.pid)
    kill $(cat /var/run/ovn/ovnsb_db.pid)
    ;;
    
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
