#!/bin/sh

# Generated by Grok 2025/Nov/03

### BEGIN INIT INFO
# Provides:          ovn-northd
# Required-Start:    $local_fs $syslog ovn-dbs
# Required-Stop:     $local_fs $syslog ovn-dbs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OVN central control daemon
# Description:       ovn-northd translates NB to SB logical flows
### END INIT INFO

# Load LSB functions (colour, log_success_msg, etc.)
. /lib/lsb/init-functions

# ---------- Configuration ----------
RUN_DIR=/var/run/ovn
LOG_DIR=/var/log/ovn
PIDFILE=$RUN_DIR/ovn-northd.pid
LOGFILE=$LOG_DIR/ovn-northd.log

NB_SOCK=$RUN_DIR/ovnnb_db.sock
SB_SOCK=$RUN_DIR/ovnsb_db.sock

# ---------- Helper: make sure dirs exist ----------
#setup_dirs() {
#    install -v -d -m 2755 "$RUN_DIR"
#    install -v -d -m 2755 "$LOG_DIR"
#}

# ---------- Start ----------
start_northd() {
    log_info_msg "Starting ovn-northd..."

    # sanity – DB sockets must exist
    if [ ! -S "$NB_SOCK" ]; then
        log_failure_msg "Northbound socket $NB_SOCK missing – start ovn-dbs first"
        return 1
    fi
    if [ ! -S "$SB_SOCK" ]; then
        log_failure_msg "Southbound socket $SB_SOCK missing – start ovn-dbs first"
        return 1
    fi

    # already running?
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
        log_success_msg "ovn-northd already running (PID $(cat $PIDFILE))"
        return 0
    fi

    # create dirs and start daemon
    #setup_dirs
    #created by ovn-dbs
    #install -v -d -m 2755 "$RUN_DIR"

    ovn-northd \
        --ovnnb-db=unix:"$NB_SOCK" \
        --ovnsb-db=unix:"$SB_SOCK" \
        --pidfile="$PIDFILE" \
        --detach \
        -vconsole:info -vfile:info \
        >>"$LOGFILE" 2>&1

    # give it a moment to write the pidfile
    sleep 1

    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
        log_success_msg "ovn-northd started (PID $(cat $PIDFILE))"
    else
        log_failure_msg "Failed to start ovn-northd – see $LOGFILE"
        return 1
    fi
}

# ---------- Stop ----------
stop_northd() {
    log_info_msg "Stopping ovn-northd..."

    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
        kill $(cat "$PIDFILE")
        rm -f "$PIDFILE"
        log_success_msg "ovn-northd stopped"
    else
        log_success_msg "ovn-northd not running"
    fi
}

# ---------- Status ----------
status_northd() {
    echo "=== ovn-northd status ==="
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
        echo "ovn-northd: RUNNING (PID $(cat $PIDFILE))"
    else
        echo "ovn-northd: STOPPED"
    fi
}

# ---------- Main ----------
case "$1" in
    start)
        start_northd
        ;;
    stop)
        stop_northd
        ;;
    restart)
        stop_northd
        sleep 1
        start_northd
        ;;
    status)
        status_northd
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
