#!/bin/sh

# Generated by Grok 2025/Oct/28

### BEGIN INIT INFO
# Provides:          memcached
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: memcached daemon
# Description:       memcached is a high-performance, distributed memory
#                    object caching system
### END INIT INFO

# Source LSB init functions
. /lib/lsb/init-functions

# Pull in sysconfig settings if available, otherwise set defaults
[ -f /etc/sysconfig/memcached ] && . /etc/sysconfig/memcached

MEMCACHED_BIN="${MEMCACHED_BIN:-/usr/bin/memcached}"
PIDFILE="${PIDFILE:-/var/run/memcached/memcached.pid}"
LOGFILE="${LOGFILE:-/var/log/memcached/memcached.log}"
USER="${USER:-memcached}"
PORT="${PORT:-11211}"
MAXCONN="${MAXCONN:-1024}"
CACHESIZE="${CACHESIZE:-64}"
OPTIONS="${OPTIONS:--l 10.0.0.11}"  # Default listen address

# If /etc/memcached.conf exists, append its content to OPTIONS
if [ -f /etc/memcached.conf ]; then
    CONF_OPTS="$(cat /etc/memcached.conf)"
    OPTIONS="${OPTIONS} ${CONF_OPTS}"
fi

# Add verbose logging and log file redirection
OPTIONS="${OPTIONS} -v"
START_OPTS="-d -p ${PORT} -u ${USER} -m ${CACHESIZE} -c ${MAXCONN} -P ${PIDFILE} ${OPTIONS} >> ${LOGFILE} 2>&1"

start() {
    log_info_msg "Starting memcached..."
    
    # Ensure directories exist
    mkdir -p /var/run/memcached /var/log/memcached
    chown ${USER}:${USER} /var/run/memcached /var/log/memcached
    
    # Start the daemon with output redirection
    start_daemon ${MEMCACHED_BIN} ${START_OPTS}
    evaluate_retval
}

stop() {
    log_info_msg "Stopping memcached..."
    killproc -p ${PIDFILE} ${MEMCACHED_BIN} -TERM
    evaluate_retval
}

case "${1}" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        ${0} stop
        sleep 1
        ${0} start
        ;;
    status)
        statusproc -p ${PIDFILE} ${MEMCACHED_BIN}
        ;;
    *)
        echo "Usage: ${0} {start|stop|restart|force-reload|status}"
        exit 1
        ;;
esac

exit 0
