#!/bin/sh
# Begin /etc/init.d/glance-api
# Description: OpenStack Glance API Service
#
###
### Generated by Grok 3 using the phrase:
###   openstack sysv
###   how to install glance from source
###   with linux from scratch 12.2?
###

NAME="glance-api"
DAEMON="/usr/bin/glance-api"
CONFIG="/etc/glance/glance-api.conf"
PIDFILE="/var/run/$NAME.pid"
LOGFILE="/var/log/glance/api.log"

start() {
    echo "Starting $NAME..."
    if [ -f "$PIDFILE" ]; then
        echo "$NAME already running."
        return 1
    fi
    su -s /bin/sh glance -c "$DAEMON --config-file=$CONFIG > $LOGFILE 2>&1 & echo \$! > $PIDFILE"
    [ $? -eq 0 ] && echo "OK" || echo "FAILED"
}

stop() {
    echo "Stopping $NAME..."
    if [ ! -f "$PIDFILE" ]; then
        echo "$NAME is not running."
        return 1
    fi
    kill $(cat "$PIDFILE")
    [ $? -eq 0 ] && rm -f "$PIDFILE" && echo "OK" || echo "FAILED"
}

status() {
    if [ -f "$PIDFILE" ]; then
        PID=$(cat "$PIDFILE")
        if ps p $PID > /dev/null 2>&1; then
            echo "$NAME is running (PID: $PID)."
            return 0
        else
            echo "$NAME PID file exists but process is not running."
            return 1
        fi
    else
        echo "$NAME is not running."
        return 3
    fi
}

case "$1" in
    start) start;;
    stop) stop;;
    restart) stop; sleep 2; start;;
    status) status;;
    *) echo "Usage: $0 {start|stop|restart|status}"; exit 1;;
esac
exit $?
# End /etc/init.d/glance-api
