#!/bin/sh
# glance-api - OpenStack Glance API Service
# chkconfig: 345 95 05

# Generated by Grok 2025/Oct/29

. /lib/lsb/init-functions

program="/usr/bin/glance-api"
config="/etc/glance/glance-api.conf"
pidfile="/var/run/glance/glance-api.pid"
logfile="/var/log/glance/glance-api.log"
user="glance"

# === SECURITY & DIRS ===
#chmod 755 /etc/glance
#chown glance:glance /etc/glance
#chmod 644 "$config"
#chown $user:$user "$config"

#mkdir -p /var/run/glance /var/log/glance
#chown $user:$user /var/run/glance /var/log/glance
#?touch "$logfile"
#?chown $user:$user "$logfile"

prepare_dirs() {
    install -v -d -m 2755 -o glance -g glance /var/run/glance
}

start() {
    log_info_msg "Starting Glance API..."
    prepare_dirs

    rm -f "$pidfile"

    # Run as glance, capture PID, write PID file as glance
    su -l $user -c "$program --config-file=$config --log-file=$logfile"' & echo $! > '"$pidfile" >/dev/null 2>&1

    # Wait and verify
    sleep 2
    if [ -f "$pidfile" ] && kill -0 $(cat "$pidfile") 2>/dev/null; then
        log_success_msg2
    else
        log_failure_msg2
        rm -f "$pidfile"
        echo "Check $logfile for errors" >&2
    fi
}

stop() {
    log_info_msg "Stopping Glance API..."
    if [ -f "$pidfile" ]; then
        kill $(cat "$pidfile") 2>/dev/null && rm -f "$pidfile"
    fi
    log_success_msg2
}

status() {
    statusproc -p "$pidfile" "$program"
}

case "$1" in
    start)   start ;;
    stop)    stop ;;
    restart) stop; sleep 2; start ;;
    status)  status ;;
    *)       echo "Usage: $0 {start|stop|restart|status}"; exit 2 ;;
esac
