#!/bin/sh
#

###
### Generated by Grok Expert 2025/Oct/20
###
###     1. Upload first /lib/lsb/init-functions
###     2. from init.d
###
### using the phrase:
###     lfs 12.4, sysv, openstack, 
###     https://docs.openstack.org/glance/2025.1/install/install-ubuntu.html as guide, 
###     attached file is located at /lib/lsb/init-functions,
###     how to install Glance from source?
###

# glance-api    OpenStack Glance API Service
#
# chkconfig:   345 95 05
# description: OpenStack Image Service API
# processname: glance-api

. /lib/lsb/init-functions

program=/usr/bin/glance-api
config=/etc/glance/glance-api.conf
pidfile=/var/run/glance/glance-api.pid
logfile=/var/log/glance/api.log

start() {
    log_info_msg "Starting Glance API"
    start_daemon -p "$pidfile" "$program" --config-file "$config" --log-file "$logfile"
    evaluate_retval
}

stop() {
    log_info_msg "Stopping Glance API"
    killproc -p "$pidfile" "$program"
    evaluate_retval
}

status() {
    statusproc -p "$pidfile" "$program"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 2
esac

exit 0
