#!/bin/sh

# generated by Grok 2025/Oct

### BEGIN INIT INFO
# Provides:          neutron-server
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OpenStack Neutron Server
# Description:       Provides the OpenStack Networking API server
### END INIT INFO

. /lib/lsb/init-functions

PROGRAM="neutron-server"
BINARY="/usr/bin/${PROGRAM}"
CONFIG_FILES="/etc/neutron/neutron.conf /etc/neutron/plugins/ml2/ml2_conf.ini"
PIDFILE="/run/${PROGRAM}.pid"
LOGFILE="/var/log/neutron/server.log"
DAEMON_ARGS="--log-file ${LOGFILE} --pid-file ${PIDFILE}"

for conf in ${CONFIG_FILES}; do
  DAEMON_ARGS="${DAEMON_ARGS} --config-file ${conf}"
done

case "$1" in
  start)
    log_info_msg "Starting ${PROGRAM}..."
    start_daemon -p "${PIDFILE}" "${BINARY}" ${DAEMON_ARGS}
    evaluate_retval
    ;;
  stop)
    log_info_msg "Stopping ${PROGRAM}..."
    killproc -p "${PIDFILE}" "${BINARY}"
    evaluate_retval
    ;;
  restart|force-reload)
    $0 stop
    $0 start
    ;;
  status)
    statusproc -p "${PIDFILE}" "${BINARY}"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
