#!/bin/sh

# Generated by Grok 2025/Oct/25

# Wrapper that starts nova‑novncproxy in the foreground and writes the pidfile
# when the process is ready.

CONFIG=/etc/nova/nova.conf
LOG=/var/log/nova/nova-novncproxy.log
PIDFILE=/run/nova-novncproxy.pid

# sanity checks
[ -f "$CONFIG" ]   || { echo "ERROR: $CONFIG missing" >&2; exit 1; }
[ -d "$(dirname "$LOG")" ] || mkdir -p "$(dirname "$LOG")"

# start in foreground, redirect output
exec /usr/bin/nova-novncproxy --config-file "$CONFIG" >>"$LOG" 2>&1
