#!/bin/sh

# Generated by Grok 2025/Oct/25

# /etc/rc.d/init.d/nova-novncproxy

. /lib/lsb/init-functions

NAME="nova-novncproxy"
DAEMON="/usr/local/bin/nova-novncproxy-wrapper"
PIDFILE="/var/run/nova/nova-novncproxy.pid"

start() {
    log_info_msg "Starting $NAME ..."

    # mkdir -p /var/run/nova /var/log/nova
    # chown nova:nova /var/run/nova /var/log/nova
    install -v -d -m 2755 -o nova -g nova /var/run/nova

    LOGFILE="/var/log/nova/nova-novncproxy.log"
    touch "$LOGFILE"
    chown nova:nova "$LOGFILE"
    chmod 644 "$LOGFILE"

    rm -f "$PIDFILE"

    setsid "$DAEMON" >/dev/null 2>&1 &
    PID=$!

    echo "$PID" > "$PIDFILE"
    chown nova:nova "$PIDFILE"

    local i=0
    while [ $i -lt 50 ]; do
        if kill -0 "$PID" 2>/dev/null; then
            log_success_msg2
            return 0
        fi
        sleep 0.1
        i=$((i+1))
    done

    log_failure_msg2
    rm -f "$PIDFILE"
    return 1
}

stop() {
    log_info_msg "Stopping $NAME ..."
    if [ -f "$PIDFILE" ]; then
        PID=$(cat "$PIDFILE")
        kill "$PID" 2>/dev/null
        local i=0
        while [ $i -lt 100 ] && kill -0 "$PID" 2>/dev/null; do
            sleep 0.1
            i=$((i+1))
        done
        kill -9 "$PID" 2>/dev/null
    fi
    rm -f "$PIDFILE"
    log_success_msg2
}

status() {
    if [ -f "$PIDFILE" ]; then
        PID=$(cat "$PIDFILE")
        if kill -0 "$PID" 2>/dev/null; then
            echo "$NAME is running with PID $PID"
            return 0
        fi
    fi
    echo "$NAME is not running"
    return 1
}

case "$1" in
    start)  start ;;
    stop)   stop  ;;
    restart) $0 stop; sleep 2; $0 start ;;
    status) status ;;
    *) echo "Usage: $0 {start|stop|restart|status}"; exit 1 ;;
esac
