#!/bin/sh

# Generated by Grok 2025/Oct/25

# /etc/rc.d/init.d/nova-novncproxy

. /lib/lsb/init-functions

NAME="nova-novncproxy"
DAEMON="/usr/bin/nova-novncproxy"
CONFIG="/etc/nova/nova.conf"
LOG="/var/log/nova/nova-novncproxy.log"
PIDFILE="/run/nova-novncproxy.pid"
USER="nova"

# Ensure directories exist
[ -d /run ] || mkdir -p /run
[ -d "$(dirname "$LOG")" ] || mkdir -p "$(dirname "$LOG")"

start() {
    log_info_msg "Starting $NAME ..."

    # Build command: run as nova user, redirect logs, write PID
    CMD="su -s /bin/sh $USER -c 'exec $DAEMON --config-file $CONFIG >>$LOG 2>&1'"

    # Use start_daemon WITHOUT -u (not supported)
    start_daemon -p "$PIDFILE" /bin/sh -c "$CMD"
    retval=$?
    evaluate_retval
    return $retval
}

stop() {
    log_info_msg "Stopping $NAME ..."
    killproc -p "$PIDFILE" "$DAEMON"
    retval=$?
    evaluate_retval
    # Clean up stale PID if needed
    [ $retval -ne 0 ] && rm -f "$PIDFILE" 2>/dev/null
    return $retval
}

status() {
    statusproc -p "$PIDFILE" "$DAEMON"
}

case "$1" in
    start)  start ;;
    stop)   stop  ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    status) status ;;
    *) echo "Usage: $0 {start|stop|restart|status}"; exit 1 ;;
esac
