#!/bin/sh

# Generated by Grok 2025/Oct/25

# /etc/rc.d/init.d/nova-novncproxy
. /lib/lsb/init-functions

NAME="nova-novncproxy"
DAEMON="/usr/local/bin/nova-novncproxy-wrapper"
PIDFILE="/run/nova-novncproxy.pid"
USER="nova"

start() { log_info_msg "Starting $NAME ..."; start_daemon -p "$PIDFILE" -u "$USER" "$DAEMON"; evaluate_retval; }
stop()  { log_info_msg "Stopping $NAME ..."; killproc -p "$PIDFILE" "$DAEMON"; evaluate_retval; rm -f "$PIDFILE" 2>/dev/null; }
status(){ statusproc -p "$PIDFILE" "$DAEMON"; }

case "$1" in start) start;; stop) stop;; restart) $0 stop; sleep 1; $0 start;; status) status;; *) echo "Usage: $0 {start|stop|restart|status}"; exit 1;; esac
