#!/bin/sh

# Generated by Grok 2025/Oct/25

# /etc/rc.d/init.d/nova-api
. /lib/lsb/init-functions

NAME="nova-api"
DAEMON="/usr/local/bin/nova-api-wrapper"
PIDFILE="/run/nova-api.pid"
USER="nova"

# -------------------------------------------------
start() {
    log_info_msg "Starting $NAME ..."
    # create /run if missing
    [ -d /run ] || mkdir -p /run
    # start as $USER, write pidfile ourselves
    start_daemon -p "$PIDFILE" -u "$USER" "$DAEMON"
    retval=$?
    evaluate_retval
    return $retval
}

stop() {
    log_info_msg "Stopping $NAME ..."
    killproc -p "$PIDFILE" "$DAEMON"
    retval=$?
    evaluate_retval
    # clean stale pidfile if killproc failed
    [ $retval -ne 0 ] && rm -f "$PIDFILE"
    return $retval
}

status() {
    statusproc -p "$PIDFILE" "$DAEMON"
}

# -------------------------------------------------
case "$1" in
    start)  start ;;
    stop)   stop  ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    status) status ;;
    *) echo "Usage: $0 {start|stop|restart|status}"; exit 1 ;;
esac
