#!/bin/sh

###
### Generated by Grok Expert 2025/Oct/20
###
###     1. Upload first /lib/lsb/init-functions
###     2. from init.d
###
### using the phrase:
###     lfs 12.4, sysv, openstack, 
###     https://docs.openstack.org/placement/2025.1/install/install-ubuntu.html as guide, 
###     attached file is located at /lib/lsb/init-functions,
###     how to install Placement from source?
###


### BEGIN INIT INFO
# Provides:          placement-api
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: OpenStack Placement API
# Description:       Provides resource provider inventories for OpenStack
### END INIT INFO

. /lib/lsb/init-functions

DAEMON=/opt/placement/venv/bin/uwsgi
DAEMON_ARGS="--http :8778 --wsgi-file /opt/placement/venv/bin/placement-api --processes 2 --threads 10 --pidfile /var/run/placement-api.pid"
PIDFILE=/var/run/placement-api.pid
LOGFILE=/var/log/placement-api.log
USER=root  # Run as root or create a 'placement' user/group for security

case "$1" in
  start)
    log_daemon_msg "Starting Placement API" "placement-api"
    start_daemon -p $PIDFILE $DAEMON $DAEMON_ARGS >> $LOGFILE 2>&1
    evaluate_retval
    ;;
  stop)
    log_daemon_msg "Stopping Placement API" "placement-api"
    killproc -p $PIDFILE $DAEMON
    evaluate_retval
    ;;
  restart|force-reload)
    $0 stop
    $0 start
    ;;
  status)
    statusproc -p $PIDFILE $DAEMON
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
